### PR TITLE
Add debugGraph

### PR DESCRIPTION
**Pull request by Mechazawa**

### CODE REVIEW

**Comment by JanWerder** [comment]
Hey, looks good. Great documentation!
What OO library is it based on? Is it class commons compatible?
Could you add a visual preview of the graph?

**Comment by Mechazawa** [comment]
It doesn't use any OO library. It uses old-school lua "OO"

```
local SomeThing = {}

function SomeThing:new()
  local instance = { beep = true }

  function instance:boop()
    if self.beep then
      print("boop")
    end
  end
end
``

**Comment by JanWerder** [comment]
Ok, nice. I will add it to the list.
Would you mind adding a screenshot of how it looks ingame?

**Comment by Mechazawa** [comment]
It looks identical to fpsGraph since it was based on it although it is incompatible. The main difference is that this re-implementation is a bit more efficient and uses a different api design.

**Pull request merged**
