### PR TITLE
Adding josefnpat's SafeWord

### PR DESCRIPTION
**Pull request by josefnpat**
I use this library when developing for android devices that require overscan detection (e.g. OUYA, Amazon Fire and GameStick)

### CODE REVIEW

**Comment by JanWerder** [comment]
I would really like to add it to the list, but would you care to a proper documentation?

**Comment by josefnpat** [comment]
That's a reasonable request! Let me make that happen.

**Comment by josefnpat** [comment]
I've been meaning to do this for a while. Thanks for the motivation.

I have fully documented the library!

https://github.com/josefnpat/safeword/blob/master/readme.md

**Comment by JanWerder** [comment]
Looks very good, now the library is more easy to understand!

**Comment by josefnpat** [comment]
:heart:

**Pull request merged**
