### PR TITLE
Added LoveShaderConverter Tool

### PR DESCRIPTION
**Pull request by tsteinholz**

### CODE REVIEW

**Comment by JanWerder** [comment]
Hi,
Thanks for the contribution.
Would you be so kind to finish the documentation first?
Also, since this is a compiled C++ Programm, could you add a compiled release first?

**Comment by tsteinholz** [comment]
Yeah no problem.

**Comment by tsteinholz** [comment]
Alright I [added documentation](https://github.com/tsteinholz/LoveShaderConverter/blob/master/docs/Quick-Guide.md) as well as added an [official build](https://github.com/tsteinholz/LoveShaderConverter/releases/)

**Comment by JanWerder** [comment]
Wow, really nicely done. Thank you!

**Pull request merged**
